wrap octave-app with `on_macos` block
because of error

```
Error: Cask 'octave-app' definition is invalid: invalid 'sha256' value: nil
Error: Process completed with exit code 1.
```